blank_issues_enabled: false
contact_links:
  - name: Exasol Personal User Documentation
    url: https://exasol.github.io/exasol-personal/
    about: Install, deploy, and use Exasol Personal
  - name: Exasol Database Documentation
    url: https://docs.exasol.com/db/latest/home.htm
    about: Official Exasol database documentation
